mixin () {
  /// Static Markdown documentation of the backend's public API.
  public query func getApiDoc() : async Text {
    "# Chart Analysis Backend\n\n"
      # "خدمة خلفية لتحليل الشارت بالذكاء الاصطناعي. تجلب بيانات الأسعار من مصادر خارجية، وتحسب المؤشرات الفنية على الخادم، وتولّد تحليلاً باللغة العربية عبر Caffeine Inference، وتحفظ النتائج لكل مستخدم.\n\n"
      # "## المصادقة والهوية\n\n"
      # "- جميع الدوال العامة تقبل الاستدعاء من أي هوية، لكن بيانات التحليلات المحفوظة مرتبطة بالمتصل (caller).\n"
      # "- الواجهة الأمامية تثبّت أصل اشتقاق Internet Identity المنشور على `/.well-known/ii-derivation-origin` عند توفره. وكيل يملك تفويض Internet Identity للمستخدم يشتق الهوية الصحيحة لكل تطبيق مقابل ذلك الأصل (مثال: `icp identity link web <name> --app <host>`). هذا التفويض يعمل بصلاحية المستخدم الكاملة في هذا التطبيق حتى انتهاء صلاحيته.\n"
      # "- لا توجد بوابة تسجيل إلزامية لاستدعاء الدوال العامة: كل الدوال العامة تقبل أي متصل، بما في ذلك المجهول (anonymous).\n"
      # "- نظام الأدوار متاح عبر `_initialize_access_control` (أول متصل غير مجهول يصبح `#admin`، والمتصلون اللاحقون `#user`) و`getCallerUserRole` و`isCallerAdmin` و`assignCallerUserRole`، لكن **لا توجد أي دالة أعمال محمية بالأدوار** في هذا التطبيق؛ الأدوار لا تُستخدم لتقييد أي من دوال السوق أو التحليل.\n"
      # "- الحماية الفعلية هي حماية الملكية (ownership): `listAnalyses` و`getAnalysis` و`deleteAnalysis` تعمل على سجلات المتصل فقط. المتصل المجهول يملك معرّفاً خاصاً به، لذا يرى سجلاته المجهولة فقط ولا يرى سجلات أي مستخدم مسجّل.\n\n"
      # "## الوحدات والترميز\n\n"
      # "- `Timestamp` بالمللي ثانية منذ حقبة Unix. الطوابع الزمنية للشموع بالمللي ثانية.\n"
      # "- `AnalysisId` رقم صحيح متزايد يبدأ من 0.\n"
      # "- الأسعار والقيم من نوع `Float`. الحجم `volume` يساوي 0.0 لمصدر CoinGecko لأنه لا يوفّره.\n"
      # "- `AssetType`: `#stock` (Yahoo Finance) أو `#crypto` (CoinGecko) أو `#forex` (أزواج العملات عبر Yahoo Finance) أو `#gold` (الذهب والفضة عبر Yahoo Finance).\n"
      # "- `Interval`: `#daily` أو `#weekly` أو `#monthly`.\n"
      # "- `Recommendation`: `#buy` أو `#sell` أو `#wait`. `confidence` رقم من 0 إلى 100.\n"
      # "- `MacdCrossover`: `#bullish` أو `#bearish` أو `#none`.\n"
      # "- `NewsItem`: `title` و`source` و`url` و`publishedAt` (بالمللي ثانية) و`summary` اختياري (`?Text`).\n"
      # "- `ExchangeHours`: `name` و`code` و`country` و`localTime` (نص الوقت المحلي) و`sessionOpen` و`sessionClose` (نصا وقت الجلسة) و`status` و`nextEvent` و`nextEventLabel` و`countdownSeconds` (عدد الثواني حتى الحدث القادم).\n"
      # "- `ExchangeStatus`: `#open` أو `#closed` أو `#preMarket` أو `#afterHours` أو `#sessionBreak` أو `#holiday`.\n"
      # "- `ExchangeEvent`: `#open` أو `#close`.\n"
      # "- `Error`: `#notFound` أو `#invalidInput` أو `#upstream` أو `#unauthorized`.\n\n"
      # "## الدوال العامة\n\n"
      # "### `searchAssets(term : Text) : async [AssetSuggestion]`\n"
      # "دالة تحديث (update) وليست استعلاماً، لأنها تنفّذ نداءات HTTP خارجية. تبحث في Yahoo Finance وCoinGecko معاً، إضافة إلى كتالوج ثابت لأزواج الفوركس (EUR/USD، GBP/USD، USD/JPY، USD/CHF، AUD/USD، USD/CAD، NZD/USD، EUR/GBP، EUR/JPY، GBP/JPY) والمعادن (الذهب `GC=F` والفضة `SI=F`)، وتعيد اقتراحات تحتوي `symbol` و`name` و`assetType` مع تصنيف واضح لكل أصل. بالنسبة للعملات الرقمية يكون `symbol` هو معرّف CoinGecko (مثل `bitcoin`) وليس رمز العملة، وبالنسبة للفوركس يكون `symbol` هو رمز Yahoo (مثل `EURUSD=X`) وبالنسبة للمعادن رمز العقود الآجلة (مثل `GC=F` أو `SI=F`)، لأن هذا ما تتطلبه دالة جلب الشموع.\n\n"
      # "### `getCandles(symbol, assetType, interval) : async Result<[Candle], Error>`\n"
      # "دالة تحديث تجلب شموع OHLCV. تُرجع `#err(#upstream(...))` عند فشل المصدر أو عدم وجود بيانات. تعمل مع الأسهم والعملات الرقمية والفوركس والذهب بنفس الشكل.\n\n"
      # "### `getIndicators(symbol, assetType, interval) : async Result<IndicatorSet, Error>`\n"
      # "دالة تحديث تجلب الشموع ثم تحسب SMA(20) وSMA(50) وRSI(14) وMACD(12,26,9) مع الهيستوجرام وإشارة التقاطع. القيم تكون `null` عندما لا تكفي البيانات.\n\n"
      # "### `generateAnalysis(request) : async Result<AnalysisResult, Error>`\n"
      # "دالة تحديث تجلب الشموع، وتحسب المؤشرات، وتبني طلباً عربياً، وتستدعي Caffeine Inference، وتحفظ النتيجة للمتصل، ثم تعيد `record` و`candles` و`indicators`. تعمل مع الأسهم والعملات الرقمية والفوركس والذهب بنفس الشكل. تستغرق ثوانٍ بسبب النداء الخارجي. تُرجع `#err(#upstream(...))` عند فشل جلب البيانات أو توليد التحليل.\n\n"
      # "### `listAnalyses() : async [AnalysisRecord]`\n"
      # "استعلام يعيد تحليلات المتصل فقط، مرتبة من الأحدث إلى الأقدم.\n\n"
      # "### `getAnalysis(id) : async ?AnalysisRecord`\n"
      # "استعلام يعيد تحليلاً واحداً إذا كان المتصل مالكه، وإلا `null`.\n\n"
      # "### `deleteAnalysis(id) : async Result<(), Error>`\n"
      # "دالة تحديث تحذف تحليلاً يملكه المتصل. تُرجع `#err(#notFound(...))` إذا لم يوجد أو لم يكن المتصل مالكه.\n\n"
      # "### `getMarketNews(keyword : ?Text, limit : Nat) : async Result<[NewsItem], Error>`\n"
      # "دالة تحديث (update) وليست استعلاماً، لأنها تنفّذ نداءات HTTP خارجية إلى مصدرين عامين للأخبار المالية: `cryptocurrency.cv` (تغطية العملات الرقمية) وخلاصة RSS مالية عامة عبر جسر `rss2json` (تغطية السلع والذهب). تُدمج نتائج المصدرين في قائمة `NewsItem` واحدة. المعامل `keyword` اختياري: عند تمريره تُجرى التصفية بالكلمة المفتاحية **داخل الكانستر** على **العنوان والملخص معاً** (مطابقة غير حساسة لحالة الأحرف)، وليس على المصدر الخارجي. المعامل `limit` يحدّ عدد العناصر المعادة. تُرجع `#err(#upstream(...))` عند فشل المصدرين معاً. لا تُحفظ الأخبار في حالة الكانستر.\n\n"
      # "### `getExchangeHours() : async Result<[ExchangeHours], Error>`\n"
      # "دالة تحديث (update) وليست استعلاماً، لأنها تنفّذ نداء HTTP خارجياً. تعيد قائمة بورصات العالم الرئيسية مع حالة التداول الحالية (`status`) والحدث المجدول القادم (`nextEvent` و`nextEventLabel`) و`countdownSeconds`. المصدر قائمة ثابتة من 13 بورصة، لذا فإن مجموعة البورصات المعادة ثابتة ولا تتغيّر حسب الطلب. تُرجع `#err(#upstream(...))` عند فشل المصدر. لا تُحفظ مواعيد البورصات في حالة الكانستر.\n\n"
      # "### `getApiDoc() : async Text`\n"
      # "استعلام يعيد هذه الوثيقة.\n\n"
      # "## دورة الحياة والاستقصاء\n\n"
      # "- `generateAnalysis` و`getCandles` و`getIndicators` و`searchAssets` و`getMarketNews` و`getExchangeHours` كلها نداءات تحديث تستغرق ثوانٍ؛ اعرض حالة انتظار في الواجهة.\n"
      # "- `listAnalyses` و`getAnalysis` استعلامات سريعة ويمكن استقصاؤها بأمان.\n"
      # "- لا توجد مهام خلفية أو حالات انتقالية؛ كل نداء يكتمل أو يفشل ضمن الاستدعاء نفسه.\n"
      # "- `getMarketNews` و`getExchangeHours` لا تحفظان شيئاً؛ يمكن استقصاؤهما دورياً لتحديث الأخبار وحالة البورصات، مع مراعاة حدود معدل المصدر الخارجي.\n\n"
      # "## أمان إعادة المحاولة\n\n"
      # "- `generateAnalysis` غير آمن للتكرار: كل استدعاء ناجح ينشئ سجلاً جديداً بمعرّف جديد. لا تعد المحاولة تلقائياً دون تأكيد المستخدم.\n"
      # "- `deleteAnalysis` آمن للتكرار: حذف معرّف محذوف مسبقاً يعيد `#err(#notFound(...))` دون أثر إضافي.\n"
      # "- `searchAssets` و`getCandles` و`getIndicators` و`getMarketNews` و`getExchangeHours` للقراءة فقط ولا تغيّر الحالة، لذا إعادة المحاولة آمنة.\n\n"
      # "## ملاحظات مهمة\n\n"
      # "- `searchAssets` و`getMarketNews` و`getExchangeHours` دوال تحديث وليست استعلامات؛ لا يمكن استدعاؤها من سياق استعلام.\n"
      # "- تصفية الأخبار بالكلمة المفتاحية تحدث داخل الكانستر على العنوان والملخص معاً، وليس على المصدر الخارجي؛ لذلك قد تعيد قائمة أقصر من `limit` أو فارغة إذا لم تطابق أي أخبار.\n"
      # "- مواعيد البورصات تأتي من قائمة ثابتة من 13 بورصة؛ لا يمكن طلب بورصة معيّنة ولا تتغيّر المجموعة حسب الطلب.\n"
      # "- المصادر الخارجية قد تحدّ من معدل الطلبات (rate limits)؛ تعامل مع `#upstream` بإعادة محاولة لاحقة.\n"
      # "- لا تُخزَّن أي مفاتيح API في الكانستر؛ بيانات اعتماد الاستدلال تأتي من المنصة وقت التشغيل.\n"
      # "- التحليلات مرتبطة بالهوية المشتقة مقابل أصل التطبيق؛ هوية مشتقة مقابل أصل مختلف تكون هوية مختلفة ولا ترى سجلات المستخدم.";
  };
};
