/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error__1 = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error__1 });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnalysisId = IDL.Nat;
export const Error = IDL.Variant({
  'invalidInput' : IDL.Text,
  'upstream' : IDL.Text,
  'notFound' : IDL.Text,
  'unauthorized' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Interval = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const AssetType = IDL.Variant({
  'forex' : IDL.Null,
  'gold' : IDL.Null,
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
});
export const AnalysisRequest = IDL.Record({
  'interval' : Interval,
  'assetType' : AssetType,
  'symbol' : IDL.Text,
});
export const Timestamp = IDL.Nat;
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const MacdCrossover = IDL.Variant({
  'bullish' : IDL.Null,
  'none' : IDL.Null,
  'bearish' : IDL.Null,
});
export const IndicatorSet = IDL.Record({
  'macdSignal' : IDL.Opt(IDL.Float64),
  'macd' : IDL.Opt(IDL.Float64),
  'sma20' : IDL.Opt(IDL.Float64),
  'sma50' : IDL.Opt(IDL.Float64),
  'macdHistogram' : IDL.Opt(IDL.Float64),
  'macdCrossover' : IDL.Opt(MacdCrossover),
  'rsi14' : IDL.Opt(IDL.Float64),
});
export const Recommendation = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
  'wait' : IDL.Null,
});
export const AnalysisRecord = IDL.Record({
  'id' : AnalysisId,
  'interval' : Interval,
  'analysisText' : IDL.Text,
  'createdAt' : Timestamp,
  'assetName' : IDL.Text,
  'assetType' : AssetType,
  'recommendation' : Recommendation,
  'confidence' : IDL.Nat,
  'priceAtAnalysis' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const AnalysisResult = IDL.Record({
  'candles' : IDL.Vec(Candle),
  'indicators' : IndicatorSet,
  'record' : AnalysisRecord,
});
export const Result_4 = IDL.Variant({ 'ok' : AnalysisResult, 'err' : Error });
export const Result_3 = IDL.Variant({ 'ok' : IDL.Vec(Candle), 'err' : Error });
export const ExchangeStatus = IDL.Variant({
  'closed' : IDL.Null,
  'preMarket' : IDL.Null,
  'sessionBreak' : IDL.Null,
  'open' : IDL.Null,
  'afterHours' : IDL.Null,
  'holiday' : IDL.Null,
});
export const ExchangeEvent = IDL.Variant({
  'close' : IDL.Null,
  'open' : IDL.Null,
});
export const ExchangeHours = IDL.Record({
  'status' : ExchangeStatus,
  'localTime' : IDL.Text,
  'nextEvent' : ExchangeEvent,
  'country' : IDL.Text,
  'sessionOpen' : IDL.Text,
  'code' : IDL.Text,
  'nextEventLabel' : IDL.Text,
  'name' : IDL.Text,
  'sessionClose' : IDL.Text,
  'countdownSeconds' : IDL.Nat,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(ExchangeHours),
  'err' : Error,
});
export const Result_1 = IDL.Variant({ 'ok' : IndicatorSet, 'err' : Error });
export const NewsItem = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'publishedAt' : Timestamp,
  'summary' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : IDL.Vec(NewsItem), 'err' : Error });
export const AssetSuggestion = IDL.Record({
  'name' : IDL.Text,
  'assetType' : AssetType,
  'symbol' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__analyses' : IDL.Func([], [IDL.Reserved], ['query']),
  '__owners' : IDL.Func([], [IDL.Reserved], ['query']),
  '__state' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_6], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnalysis' : IDL.Func([AnalysisId], [Result_5], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'generateAnalysis' : IDL.Func([AnalysisRequest], [Result_4], []),
  'getAnalysis' : IDL.Func([AnalysisId], [IDL.Opt(AnalysisRecord)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandles' : IDL.Func([IDL.Text, AssetType, Interval], [Result_3], []),
  'getExchangeHours' : IDL.Func([], [Result_2], []),
  'getIndicators' : IDL.Func([IDL.Text, AssetType, Interval], [Result_1], []),
  'getMarketNews' : IDL.Func([IDL.Opt(IDL.Text), IDL.Nat], [Result], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchAssets' : IDL.Func([IDL.Text], [IDL.Vec(AssetSuggestion)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error__1 = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error__1 });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnalysisId = IDL.Nat;
  const Error = IDL.Variant({
    'invalidInput' : IDL.Text,
    'upstream' : IDL.Text,
    'notFound' : IDL.Text,
    'unauthorized' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Interval = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const AssetType = IDL.Variant({
    'forex' : IDL.Null,
    'gold' : IDL.Null,
    'stock' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const AnalysisRequest = IDL.Record({
    'interval' : Interval,
    'assetType' : AssetType,
    'symbol' : IDL.Text,
  });
  const Timestamp = IDL.Nat;
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const MacdCrossover = IDL.Variant({
    'bullish' : IDL.Null,
    'none' : IDL.Null,
    'bearish' : IDL.Null,
  });
  const IndicatorSet = IDL.Record({
    'macdSignal' : IDL.Opt(IDL.Float64),
    'macd' : IDL.Opt(IDL.Float64),
    'sma20' : IDL.Opt(IDL.Float64),
    'sma50' : IDL.Opt(IDL.Float64),
    'macdHistogram' : IDL.Opt(IDL.Float64),
    'macdCrossover' : IDL.Opt(MacdCrossover),
    'rsi14' : IDL.Opt(IDL.Float64),
  });
  const Recommendation = IDL.Variant({
    'buy' : IDL.Null,
    'sell' : IDL.Null,
    'wait' : IDL.Null,
  });
  const AnalysisRecord = IDL.Record({
    'id' : AnalysisId,
    'interval' : Interval,
    'analysisText' : IDL.Text,
    'createdAt' : Timestamp,
    'assetName' : IDL.Text,
    'assetType' : AssetType,
    'recommendation' : Recommendation,
    'confidence' : IDL.Nat,
    'priceAtAnalysis' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const AnalysisResult = IDL.Record({
    'candles' : IDL.Vec(Candle),
    'indicators' : IndicatorSet,
    'record' : AnalysisRecord,
  });
  const Result_4 = IDL.Variant({ 'ok' : AnalysisResult, 'err' : Error });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Vec(Candle), 'err' : Error });
  const ExchangeStatus = IDL.Variant({
    'closed' : IDL.Null,
    'preMarket' : IDL.Null,
    'sessionBreak' : IDL.Null,
    'open' : IDL.Null,
    'afterHours' : IDL.Null,
    'holiday' : IDL.Null,
  });
  const ExchangeEvent = IDL.Variant({ 'close' : IDL.Null, 'open' : IDL.Null });
  const ExchangeHours = IDL.Record({
    'status' : ExchangeStatus,
    'localTime' : IDL.Text,
    'nextEvent' : ExchangeEvent,
    'country' : IDL.Text,
    'sessionOpen' : IDL.Text,
    'code' : IDL.Text,
    'nextEventLabel' : IDL.Text,
    'name' : IDL.Text,
    'sessionClose' : IDL.Text,
    'countdownSeconds' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(ExchangeHours),
    'err' : Error,
  });
  const Result_1 = IDL.Variant({ 'ok' : IndicatorSet, 'err' : Error });
  const NewsItem = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'publishedAt' : Timestamp,
    'summary' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Vec(NewsItem), 'err' : Error });
  const AssetSuggestion = IDL.Record({
    'name' : IDL.Text,
    'assetType' : AssetType,
    'symbol' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__analyses' : IDL.Func([], [IDL.Reserved], ['query']),
    '__owners' : IDL.Func([], [IDL.Reserved], ['query']),
    '__state' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_6], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnalysis' : IDL.Func([AnalysisId], [Result_5], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'generateAnalysis' : IDL.Func([AnalysisRequest], [Result_4], []),
    'getAnalysis' : IDL.Func(
        [AnalysisId],
        [IDL.Opt(AnalysisRecord)],
        ['query'],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandles' : IDL.Func([IDL.Text, AssetType, Interval], [Result_3], []),
    'getExchangeHours' : IDL.Func([], [Result_2], []),
    'getIndicators' : IDL.Func([IDL.Text, AssetType, Interval], [Result_1], []),
    'getMarketNews' : IDL.Func([IDL.Opt(IDL.Text), IDL.Nat], [Result], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchAssets' : IDL.Func([IDL.Text], [IDL.Vec(AssetSuggestion)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };