/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisId = bigint;
export interface AnalysisRecord {
  'id' : AnalysisId,
  'interval' : Interval,
  'analysisText' : string,
  'createdAt' : Timestamp,
  'assetName' : string,
  'assetType' : AssetType,
  'recommendation' : Recommendation,
  'confidence' : bigint,
  'priceAtAnalysis' : number,
  'symbol' : string,
}
export interface AnalysisRequest {
  'interval' : Interval,
  'assetType' : AssetType,
  'symbol' : string,
}
export interface AnalysisResult {
  'candles' : Array<Candle>,
  'indicators' : IndicatorSet,
  'record' : AnalysisRecord,
}
export interface AssetSuggestion {
  'name' : string,
  'assetType' : AssetType,
  'symbol' : string,
}
export type AssetType = { 'forex' : null } |
  { 'gold' : null } |
  { 'stock' : null } |
  { 'crypto' : null };
export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : number,
  'timestamp' : Timestamp,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'invalidInput' : string } |
  { 'upstream' : string } |
  { 'notFound' : string } |
  { 'unauthorized' : string };
export type Error__1 = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExchangeEvent = { 'close' : null } |
  { 'open' : null };
export interface ExchangeHours {
  'status' : ExchangeStatus,
  'localTime' : string,
  'nextEvent' : ExchangeEvent,
  'country' : string,
  'sessionOpen' : string,
  'code' : string,
  'nextEventLabel' : string,
  'name' : string,
  'sessionClose' : string,
  'countdownSeconds' : bigint,
}
export type ExchangeStatus = { 'closed' : null } |
  { 'preMarket' : null } |
  { 'sessionBreak' : null } |
  { 'open' : null } |
  { 'afterHours' : null } |
  { 'holiday' : null };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface IndicatorSet {
  'macdSignal' : [] | [number],
  'macd' : [] | [number],
  'sma20' : [] | [number],
  'sma50' : [] | [number],
  'macdHistogram' : [] | [number],
  'macdCrossover' : [] | [MacdCrossover],
  'rsi14' : [] | [number],
}
export type Interval = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type MacdCrossover = { 'bullish' : null } |
  { 'none' : null } |
  { 'bearish' : null };
export interface NewsItem {
  'url' : string,
  'title' : string,
  'source' : string,
  'publishedAt' : Timestamp,
  'summary' : [] | [string],
}
export type Recommendation = { 'buy' : null } |
  { 'sell' : null } |
  { 'wait' : null };
export type Result = { 'ok' : Array<NewsItem> } |
  { 'err' : Error };
export type Result_1 = { 'ok' : IndicatorSet } |
  { 'err' : Error };
export type Result_2 = { 'ok' : Array<ExchangeHours> } |
  { 'err' : Error };
export type Result_3 = { 'ok' : Array<Candle> } |
  { 'err' : Error };
export type Result_4 = { 'ok' : AnalysisResult } |
  { 'err' : Error };
export type Result_5 = { 'ok' : null } |
  { 'err' : Error };
export type Result_6 = { 'ok' : null } |
  { 'err' : Error__1 };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__analyses' : ActorMethod<[], any>,
  '__owners' : ActorMethod<[], any>,
  '__state' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_6>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Delete one saved analysis by id (owner only).
   */
  'deleteAnalysis' : ActorMethod<[AnalysisId], Result_5>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Fetch price history, compute indicators, generate an Arabic AI analysis,
   * / persist it, and return the full result.
   */
  'generateAnalysis' : ActorMethod<[AnalysisRequest], Result_4>,
  /**
   * / Fetch one saved analysis by id (owner only).
   */
  'getAnalysis' : ActorMethod<[AnalysisId], [] | [AnalysisRecord]>,
  /**
   * / Static Markdown documentation of the backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch OHLC candles for an asset and interval.
   */
  'getCandles' : ActorMethod<[string, AssetType, Interval], Result_3>,
  /**
   * / Fetch the world's major exchanges with their current trading status and
   * / the next scheduled open/close event. Read-only: performs an HTTP outcall
   * / to a public exchange-hours source.
   */
  'getExchangeHours' : ActorMethod<[], Result_2>,
  /**
   * / Compute technical indicators for an asset and interval.
   */
  'getIndicators' : ActorMethod<[string, AssetType, Interval], Result_1>,
  /**
   * / Fetch the latest financial news, optionally filtered by a keyword and
   * / capped at `limit` items. Read-only: performs an HTTP outcall to a public
   * / news source.
   */
  'getMarketNews' : ActorMethod<[[] | [string], bigint], Result>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's saved analyses, newest first.
   */
  'listAnalyses' : ActorMethod<[], Array<AnalysisRecord>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search stocks, cryptocurrencies, forex pairs and precious metals by name
   * / or symbol. This is an update call because it performs HTTP outcalls to
   * / the upstream sources.
   */
  'searchAssets' : ActorMethod<[string], Array<AssetSuggestion>>,
  /**
   * / HTTP outcall transform. Strips response headers so the response is
   * / deterministic across replicas.
   */
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];