/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type AnalysisId = bigint;
export interface AnalysisRecord {
    id: AnalysisId;
    interval: Interval;
    analysisText: string;
    createdAt: Timestamp;
    assetName: string;
    assetType: AssetType;
    recommendation: Recommendation;
    confidence: bigint;
    priceAtAnalysis: number;
    symbol: string;
}
export interface AnalysisRequest {
    interval: Interval;
    assetType: AssetType;
    symbol: string;
}
export interface AnalysisResult {
    candles: Array<Candle>;
    indicators: IndicatorSet;
    record: AnalysisRecord;
}
export interface AssetSuggestion {
    name: string;
    assetType: AssetType;
    symbol: string;
}
export interface Candle {
    low: number;
    high: number;
    close: number;
    open: number;
    volume: number;
    timestamp: Timestamp;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Error_ = {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "upstream";
    upstream: string;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
};
export type Error__1 = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface ExchangeHours {
    status: ExchangeStatus;
    localTime: string;
    nextEvent: ExchangeEvent;
    country: string;
    sessionOpen: string;
    code: string;
    nextEventLabel: string;
    name: string;
    sessionClose: string;
    countdownSeconds: bigint;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface IndicatorSet {
    macdSignal?: number;
    macd?: number;
    sma20?: number;
    sma50?: number;
    macdHistogram?: number;
    macdCrossover?: MacdCrossover;
    rsi14?: number;
}
export interface NewsItem {
    url: string;
    title: string;
    source: string;
    publishedAt: Timestamp;
    summary?: string;
}
export type Result = {
    __kind__: "ok";
    ok: Array<NewsItem>;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_1 = {
    __kind__: "ok";
    ok: IndicatorSet;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_2 = {
    __kind__: "ok";
    ok: Array<ExchangeHours>;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Array<Candle>;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_4 = {
    __kind__: "ok";
    ok: AnalysisResult;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_5 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_6 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error__1;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Timestamp = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum AssetType {
    forex = "forex",
    gold = "gold",
    stock = "stock",
    crypto = "crypto"
}
export enum ExchangeEvent {
    close = "close",
    open = "open"
}
export enum ExchangeStatus {
    closed = "closed",
    preMarket = "preMarket",
    sessionBreak = "sessionBreak",
    open = "open",
    afterHours = "afterHours",
    holiday = "holiday"
}
export enum Interval {
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum MacdCrossover {
    bullish = "bullish",
    none = "none",
    bearish = "bearish"
}
export enum Recommendation {
    buy = "buy",
    sell = "sell",
    wait = "wait"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __analyses(): Promise<any>;
    __owners(): Promise<any>;
    __state(): Promise<any>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_6>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Delete one saved analysis by id (owner only).
     */
    deleteAnalysis(id: AnalysisId): Promise<Result_5>;
    execute(qJson: string): Promise<Result__1>;
    /**
     * / Fetch price history, compute indicators, generate an Arabic AI analysis,
     * / persist it, and return the full result.
     */
    generateAnalysis(request: AnalysisRequest): Promise<Result_4>;
    /**
     * / Fetch one saved analysis by id (owner only).
     */
    getAnalysis(id: AnalysisId): Promise<AnalysisRecord | null>;
    /**
     * / Static Markdown documentation of the backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch OHLC candles for an asset and interval.
     */
    getCandles(symbol_: string, assetType: AssetType, interval: Interval): Promise<Result_3>;
    /**
     * / Fetch the world's major exchanges with their current trading status and
     * / the next scheduled open/close event. Read-only: performs an HTTP outcall
     * / to a public exchange-hours source.
     */
    getExchangeHours(): Promise<Result_2>;
    /**
     * / Compute technical indicators for an asset and interval.
     */
    getIndicators(symbol_: string, assetType: AssetType, interval: Interval): Promise<Result_1>;
    /**
     * / Fetch the latest financial news, optionally filtered by a keyword and
     * / capped at `limit` items. Read-only: performs an HTTP outcall to a public
     * / news source.
     */
    getMarketNews(keyword: string | null, limit: bigint): Promise<Result>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the caller's saved analyses, newest first.
     */
    listAnalyses(): Promise<Array<AnalysisRecord>>;
    schema(): Promise<string>;
    /**
     * / Search stocks, cryptocurrencies, forex pairs and precious metals by name
     * / or symbol. This is an update call because it performs HTTP outcalls to
     * / the upstream sources.
     */
    searchAssets(term: string): Promise<Array<AssetSuggestion>>;
    /**
     * / HTTP outcall transform. Strips response headers so the response is
     * / deterministic across replicas.
     */
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AnalysisId as _AnalysisId, AnalysisRecord as _AnalysisRecord, AnalysisRequest as _AnalysisRequest, AnalysisResult as _AnalysisResult, AssetSuggestion as _AssetSuggestion, AssetType as _AssetType, Candle as _Candle, Cell as _Cell, Error as _Error, Error__1 as _Error__1, ExchangeEvent as _ExchangeEvent, ExchangeHours as _ExchangeHours, ExchangeStatus as _ExchangeStatus, IndicatorSet as _IndicatorSet, Interval as _Interval, MacdCrossover as _MacdCrossover, NewsItem as _NewsItem, Recommendation as _Recommendation, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result__1 as _Result__1, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __analyses(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__analyses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__analyses();
            return result;
        }
    }
    async __owners(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__owners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__owners();
            return result;
        }
    }
    async __state(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__state();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__state();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAnalysis(arg0: AnalysisId): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0);
                return from_candid_Result_5_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0);
            return from_candid_Result_5_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateAnalysis(arg0: AnalysisRequest): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAnalysis(to_candid_AnalysisRequest_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_4_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAnalysis(to_candid_AnalysisRequest_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_4_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysis(arg0: AnalysisId): Promise<AnalysisRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandles(arg0: string, arg1: AssetType, arg2: Interval): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandles(arg0, to_candid_AssetType_n21(this._uploadFile, this._downloadFile, arg1), to_candid_Interval_n20(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_3_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandles(arg0, to_candid_AssetType_n21(this._uploadFile, this._downloadFile, arg1), to_candid_Interval_n20(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_3_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExchangeHours(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeHours();
                return from_candid_Result_2_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeHours();
            return from_candid_Result_2_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIndicators(arg0: string, arg1: AssetType, arg2: Interval): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getIndicators(arg0, to_candid_AssetType_n21(this._uploadFile, this._downloadFile, arg1), to_candid_Interval_n20(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_1_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIndicators(arg0, to_candid_AssetType_n21(this._uploadFile, this._downloadFile, arg1), to_candid_Interval_n20(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_1_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketNews(arg0: string | null, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketNews(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketNews(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAnalyses(): Promise<Array<AnalysisRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalyses();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalyses();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchAssets(arg0: string): Promise<Array<AssetSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAssets(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAssets(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AnalysisRecord_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisRecord): AnalysisRecord {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResult): AnalysisResult {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_AssetSuggestion_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetSuggestion): AssetSuggestion {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_AssetType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetType): AssetType {
    return "forex" in value ? AssetType.forex : "gold" in value ? AssetType.gold : "stock" in value ? AssetType.stock : "crypto" in value ? AssetType.crypto : value;
}
function from_candid_Cell_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Error__1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error__1): Error__1 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ExchangeEvent_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExchangeEvent): ExchangeEvent {
    return "close" in value ? ExchangeEvent.close : "open" in value ? ExchangeEvent.open : value;
}
function from_candid_ExchangeHours_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExchangeHours): ExchangeHours {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ExchangeStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExchangeStatus): ExchangeStatus {
    return "closed" in value ? ExchangeStatus.closed : "preMarket" in value ? ExchangeStatus.preMarket : "sessionBreak" in value ? ExchangeStatus.sessionBreak : "open" in value ? ExchangeStatus.open : "afterHours" in value ? ExchangeStatus.afterHours : "holiday" in value ? ExchangeStatus.holiday : value;
}
function from_candid_IndicatorSet_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndicatorSet): IndicatorSet {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Interval_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interval): Interval {
    return "monthly" in value ? Interval.monthly : "daily" in value ? Interval.daily : "weekly" in value ? Interval.weekly : value;
}
function from_candid_MacdCrossover_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MacdCrossover): MacdCrossover {
    return "bullish" in value ? MacdCrossover.bullish : "none" in value ? MacdCrossover.none : "bearish" in value ? MacdCrossover.bearish : value;
}
function from_candid_NewsItem_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsItem): NewsItem {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Recommendation_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendation): Recommendation {
    return "buy" in value ? Recommendation.buy : "sell" in value ? Recommendation.sell : "wait" in value ? Recommendation.wait : value;
}
function from_candid_Result_1_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MacdCrossover]): MacdCrossover | null {
    return value.length === 0 ? null : from_candid_MacdCrossover_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnalysisRecord]): AnalysisRecord | null {
    return value.length === 0 ? null : from_candid_AnalysisRecord_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n12(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n16(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    candles: Array<_Candle>;
    indicators: _IndicatorSet;
    record: _AnalysisRecord;
}): {
    candles: Array<Candle>;
    indicators: IndicatorSet;
    record: AnalysisRecord;
} {
    return {
        candles: value.candles,
        indicators: from_candid_IndicatorSet_n26(_uploadFile, _downloadFile, value.indicators),
        record: from_candid_AnalysisRecord_n31(_uploadFile, _downloadFile, value.record)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    macdSignal: [] | [number];
    macd: [] | [number];
    sma20: [] | [number];
    sma50: [] | [number];
    macdHistogram: [] | [number];
    macdCrossover: [] | [_MacdCrossover];
    rsi14: [] | [number];
}): {
    macdSignal?: number;
    macd?: number;
    sma20?: number;
    sma50?: number;
    macdHistogram?: number;
    macdCrossover?: MacdCrossover;
    rsi14?: number;
} {
    return {
        macdSignal: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.macdSignal)),
        macd: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.macd)),
        sma20: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.sma20)),
        sma50: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.sma50)),
        macdHistogram: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.macdHistogram)),
        macdCrossover: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.macdCrossover)),
        rsi14: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.rsi14))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnalysisId;
    interval: _Interval;
    analysisText: string;
    createdAt: _Timestamp;
    assetName: string;
    assetType: _AssetType;
    recommendation: _Recommendation;
    confidence: bigint;
    priceAtAnalysis: number;
    symbol: string;
}): {
    id: AnalysisId;
    interval: Interval;
    analysisText: string;
    createdAt: Timestamp;
    assetName: string;
    assetType: AssetType;
    recommendation: Recommendation;
    confidence: bigint;
    priceAtAnalysis: number;
    symbol: string;
} {
    return {
        id: value.id,
        interval: from_candid_Interval_n33(_uploadFile, _downloadFile, value.interval),
        analysisText: value.analysisText,
        createdAt: value.createdAt,
        assetName: value.assetName,
        assetType: from_candid_AssetType_n34(_uploadFile, _downloadFile, value.assetType),
        recommendation: from_candid_Recommendation_n35(_uploadFile, _downloadFile, value.recommendation),
        confidence: value.confidence,
        priceAtAnalysis: value.priceAtAnalysis,
        symbol: value.symbol
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ExchangeStatus;
    localTime: string;
    nextEvent: _ExchangeEvent;
    country: string;
    sessionOpen: string;
    code: string;
    nextEventLabel: string;
    name: string;
    sessionClose: string;
    countdownSeconds: bigint;
}): {
    status: ExchangeStatus;
    localTime: string;
    nextEvent: ExchangeEvent;
    country: string;
    sessionOpen: string;
    code: string;
    nextEventLabel: string;
    name: string;
    sessionClose: string;
    countdownSeconds: bigint;
} {
    return {
        status: from_candid_ExchangeStatus_n45(_uploadFile, _downloadFile, value.status),
        localTime: value.localTime,
        nextEvent: from_candid_ExchangeEvent_n46(_uploadFile, _downloadFile, value.nextEvent),
        country: value.country,
        sessionOpen: value.sessionOpen,
        code: value.code,
        nextEventLabel: value.nextEventLabel,
        name: value.name,
        sessionClose: value.sessionClose,
        countdownSeconds: value.countdownSeconds
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: string;
    source: string;
    publishedAt: _Timestamp;
    summary: [] | [string];
}): {
    url: string;
    title: string;
    source: string;
    publishedAt: Timestamp;
    summary?: string;
} {
    return {
        url: value.url,
        title: value.title,
        source: value.source,
        publishedAt: value.publishedAt,
        summary: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.summary))
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    assetType: _AssetType;
    symbol: string;
}): {
    name: string;
    assetType: AssetType;
    symbol: string;
} {
    return {
        name: value.name,
        assetType: from_candid_AssetType_n34(_uploadFile, _downloadFile, value.assetType),
        symbol: value.symbol
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error__1;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error__1;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error__1_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AnalysisResult;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: AnalysisResult;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AnalysisResult_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Candle>;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: Array<Candle>;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ExchangeHours>;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: Array<ExchangeHours>;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n42(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _IndicatorSet;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: IndicatorSet;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_IndicatorSet_n26(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_NewsItem>;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: Array<NewsItem>;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n52(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidInput: string;
} | {
    upstream: string;
} | {
    notFound: string;
} | {
    unauthorized: string;
}): {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "upstream";
    upstream: string;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
} {
    return "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "upstream" in value ? {
        __kind__: "upstream",
        upstream: value.upstream
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExchangeHours>): Array<ExchangeHours> {
    return value.map((x)=>from_candid_ExchangeHours_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsItem>): Array<NewsItem> {
    return value.map((x)=>from_candid_NewsItem_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisRecord>): Array<AnalysisRecord> {
    return value.map((x)=>from_candid_AnalysisRecord_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetSuggestion>): Array<AssetSuggestion> {
    return value.map((x)=>from_candid_AssetSuggestion_n58(_uploadFile, _downloadFile, x));
}
function to_candid_AnalysisRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisRequest): _AnalysisRequest {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_AssetType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): _AssetType {
    return value == AssetType.forex ? {
        forex: null
    } : value == AssetType.gold ? {
        gold: null
    } : value == AssetType.stock ? {
        stock: null
    } : value == AssetType.crypto ? {
        crypto: null
    } : value;
}
function to_candid_Interval_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Interval): _Interval {
    return value == Interval.monthly ? {
        monthly: null
    } : value == Interval.daily ? {
        daily: null
    } : value == Interval.weekly ? {
        weekly: null
    } : value;
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interval: Interval;
    assetType: AssetType;
    symbol: string;
}): {
    interval: _Interval;
    assetType: _AssetType;
    symbol: string;
} {
    return {
        interval: to_candid_Interval_n20(_uploadFile, _downloadFile, value.interval),
        assetType: to_candid_AssetType_n21(_uploadFile, _downloadFile, value.assetType),
        symbol: value.symbol
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
